-- Populate empreendimento column for historical/discontinued empreendimentos
UPDATE squad_deals SET empreendimento = CASE empreendimento_id
  WHEN '4090' THEN 'Canas Beach Spot'
  WHEN '4292' THEN 'Novo Campeche Spot'
  WHEN '4056' THEN 'Foz Spot'
  WHEN '3489' THEN 'Ponta das Canas Spot'
  WHEN '2526' THEN 'Urubici Spot II'
  WHEN '3298' THEN 'Santinho Spot'
  WHEN '3158' THEN 'Meireles Spot'
  WHEN '492' THEN 'Aguardando definição'
  WHEN '1447' THEN 'Salvador Spot'
  WHEN '2840' THEN 'Batel Spot'
  WHEN '828' THEN 'Imbassaí Spot'
  WHEN '1171' THEN 'Trancoso Spot'
  WHEN '466' THEN 'Japaratinga Spot'
  WHEN '3303' THEN 'Bonito Spot'
  WHEN '464' THEN 'Ingleses Spot'
  WHEN '465' THEN 'Urubici Spot'
  WHEN '3201' THEN 'Ilha do Campeche II Spot'
  WHEN '463' THEN 'Rosa Sul Spot'
  WHEN '2868' THEN 'Sul da Ilha Spot'
  WHEN '2885' THEN 'Morro das Pedras Spot'
  WHEN '3119' THEN 'Santo Antônio Spot'
  WHEN '3266' THEN 'Cachoeira Beach Spot'
  WHEN '461' THEN 'Vistas de Anitá I'
  WHEN '2573' THEN 'Canasvieiras Spot'
  WHEN '490' THEN 'Penha Spot'
  WHEN '2324' THEN 'Campeche Spot'
  WHEN '506' THEN 'Jurerê Spot'
  WHEN '3313' THEN 'Altavista'
  WHEN '692' THEN 'Canela Spot'
  WHEN '3470' THEN 'spot teste'
  ELSE empreendimento
END
WHERE empreendimento IS NULL AND empreendimento_id != '';
